// Auto-generated by script. Do not edit manually.
const ALL_GAMES = ['/bloodmoney', '/snow-rider-2', '/drift-boss', '/subway-surfers', '/snow-rush-3d', '/slope-rider', '/slide-down-slope', '/slope-3-online', '/slope-multiplayer', '/gate-rusher-2', '/two-ball-3d-dark', '/slope-spooky', '/slope-2', '/slope-snowball', '/survive-lava-for-brainrots', '/fastlaners', '/fall-guyz', '/parkour-craft-noob-steve', '/dinosaur-city-hunting-destroy', '/extreme-ball-balancer-3d', '/finns-ascent', '/up-together', '/speed-stars', '/ski-frenzy', '/super-traffic-racer', '/drift-hunters-2', '/stunt-bike-extreme', '/g-switch-2', '/santa-run', '/subway-surfers-winter-holiday'];

/** Slug -> title for search and listings */
const GAME_TITLES = {
  '/bloodmoney': 'BLOODMONEY', '/snow-rider-2': 'Snow Rider 2', '/drift-boss': 'Drift Boss',
  '/subway-surfers': 'Subway Surfers', '/snow-rush-3d': 'Snow Rush 3D', '/slope-rider': 'Slope Rider',
  '/slide-down-slope': 'Slide Down Slope', '/slope-3-online': 'Slope 3 Online', '/slope-multiplayer': 'Slope Multiplayer',
  '/gate-rusher-2': 'Gate Rusher 2', '/two-ball-3d-dark': 'Two Ball 3D: Dark', '/slope-spooky': 'Slope Spooky',
  '/slope-2': 'Slope 2', '/slope-snowball': 'Slope Snowball', '/survive-lava-for-brainrots': 'Survive Lava for Brainrots!',
  '/fastlaners': 'FastLaners', '/fall-guyz': 'Fall Guyz', '/parkour-craft-noob-steve': 'Parkour Craft Noob Steve',
  '/dinosaur-city-hunting-destroy': 'Dinosaur City Hunting Destroy', '/extreme-ball-balancer-3d': 'Extreme Ball Balancer 3D',
  '/finns-ascent': "Finn's Ascent", '/up-together': 'Up Together', '/speed-stars': 'Speed Stars',
  '/ski-frenzy': 'Ski Frenzy', '/super-traffic-racer': 'Super Traffic Racer', '/drift-hunters-2': 'Drift Hunters 2',
  '/stunt-bike-extreme': 'Stunt Bike Extreme', '/g-switch-2': 'G-Switch 2', '/santa-run': 'Santa Run',
  '/subway-surfers-winter-holiday': 'Subway Surfers Winter Holiday'
};